### ISSUE TITLE
unity 5.4.0p3 error exporting models

### ISSUE THREAD

**Issue by KekMcGee** [Perfare/UnityStudio#11]
************** Exception Text **************
System.OutOfMemoryException: Array dimensions exceeded supported range.
   at Unity_Studio.SkinnedMeshRenderer..ctor(AssetPreloadData preloadData)
   at Unity_Studio.UnityStudioForm.WriteFBX(String FBXfile, Boolean allNodes)
   at Unity_Studio.UnityStudioForm.Export3DObjects_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Here's the file in question https://mega.nz/#!JwQCBbpA!3Z8iAVOmlwsVXl2W7b8dtYwKQvVueWmsGNdM0bosBoQ

**Comment by Perfare** [comment]
I think the new code has solved this problem.

**Comment by KekMcGee** [comment]
Thanks, It looks like most things export now, but there are still some things that aren't exporting geometry. 

https://mega.nz/#!114EQKAY!2e-A3FvzmjMBKqIv4a54IHfbMO9KyOrUpta2FkikUH4

I don't know if it'd be reasonable to upload all the assetbundles or if that would be a big no no.
