### ISSUE TITLE
Unity 5.3.5p7 error exporting models

### ISSUE THREAD

**Issue by kohos** [Perfare/UnityStudio#14]
Sorry to disturb you but I got an error like this:
************** Exception Text **************
System.OutOfMemoryException: Array dimensions exceeded supported range.
   at Unity_Studio.Mesh..ctor(AssetPreloadData MeshPD)
   at Unity_Studio.UnityStudioForm.WriteFBX(String FBXfile, Boolean allNodes)
   at Unity_Studio.UnityStudioForm.Export3DObjects_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

UnityStudio version: v0.6.5
Here is the file in question
https://pan.baidu.com/s/1hsG8lrm

Although I can export this bundle with older version of UnityStudio, I got errors when I import the FBX file to Unity.

**Comment by Perfare** [comment]
OK,I found that I made a mistake in the new version
import FBX file to 3ds MAX then export obj file should be able to work properly

**Comment by kohos** [comment]
Thanks. This issue has been fixed with the commit [3b7b88b](https://github.com/Perfare/UnityStudio/commit/3b7b88be5747eb32b0986f6697107d1d3d0f196f)
