### ISSUE TITLE
Unhandled Exception | "Could not find a part of the path"

### ISSUE THREAD

**Issue by ZenofyMedia** [Perfare/UnityStudio#621]
Trying to use Asset Studio on an unreleased Unity Game to make artwork for a thumbnail; however after successfully loading some assets, I get the error listed below with the message in the title. 

> See the end of this message for details on invoking 
> just-in-time (JIT) debugging instead of this dialog box.
> 
> Exception Text
> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Program Files (x86)\Steam\steamapps\common\Screaming Chicken!\Screaming Chicken Ultimate Showdown_Data\StreamingAssets\windows\assets\assetbundles\fx\bulletprefabs\bullet\bullet_blazingred\bullet_small_blazingred\bullet_blazingred_small_impact.unity3d.manifest'.
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
>    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
>    at AssetStudio.ImportHelper.CheckFileType(String fileName, EndianBinaryReader& reader) in C:\projects\assetstudio\AssetStudio\ImportHelper.cs:line 68
>    at AssetStudio.AssetsManager.LoadFile(String fullName) in C:\projects\assetstudio\AssetStudio\AssetsManager.cs:line 61
>    at AssetStudio.AssetsManager.Load(String[] files) in C:\projects\assetstudio\AssetStudio\AssetsManager.cs:line 48
>    at System.Threading.Tasks.Task.Execute()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at AssetStudioGUI.AssetStudioGUIForm.<loadFolder_Click>d__49.MoveNext() in C:\projects\assetstudio\AssetStudioGUI\AssetStudioGUIForm.cs:line 149
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> 
> Loaded Assemblies 
> mscorlib
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
>     CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
> 
> AssetStudioGUI
>     Assembly Version: 0.15.23.0
>     Win32 Version: 0.15.23
>     CodeBase: file:///Z:/Graphics/AssetStudio.v0.15.5/AssetStudioGUI.exe
> 
> System.Windows.Forms
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
>     CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
>
> System
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C
>     CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
> 
> System.Drawing
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.3752.0 built by: NET48REL1
>     CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
> 
> AssetStudioUtility
>     Assembly Version: 0.15.23.0
>     Win32 Version: 0.15.23
>     CodeBase: file:///Z:/Graphics/AssetStudio.v0.15.5/AssetStudioUtility.DLL
> 
> OpenTK
>     Assembly Version: 3.1.0.0
>     Win32 Version: 3.1.0
>     CodeBase: file:///Z:/Graphics/AssetStudio.v0.15.5/OpenTK.DLL
> 
> AssetStudio
>     Assembly Version: 0.15.23.0
>     Win32 Version: 0.15.23
>     CodeBase: file:///Z:/Graphics/AssetStudio.v0.15.5/AssetStudio.DLL
> System.Core
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4220.0 built by: NET48REL1LAST_C
>     CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
>
> Unity.Cecil
>     Assembly Version: 0.10.0.0
>     Win32 Version: 0.10.0.0
>     CodeBase: file:///Z:/Graphics/AssetStudio.v0.15.5/Unity.Cecil.DLL
> 
> System.Configuration
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
>     CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
>
> System.Xml
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.3752.0 built by: NET48REL1
>     CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
>
> OpenTK.GLControl
>     Assembly Version: 3.1.0.0
>     Win32 Version: 3.1.0
>     CodeBase: file:///Z:/Graphics/AssetStudio.v0.15.5/OpenTK.GLControl.DLL
>
> AssetStudio.PInvoke
>     Assembly Version: 0.15.23.0
>     Win32 Version: 0.15.23
>     CodeBase: file:///Z:/Graphics/AssetStudio.v0.15.5/AssetStudio.PInvoke.DLL
>
> 
> JIT Debugging
> To enable just-in-time (JIT) debugging, the .config file for this
> application or computer (machine.config) must have the
> jitDebugging value set in the system.windows.forms section.
> The application must also be compiled with debugging
> enabled.
> 
> For example:
> 
> <configuration>
>     <system.windows.forms jitDebugging="true" />
> </configuration>
> 
> When JIT debugging is enabled, any unhandled exception
> will be sent to the JIT debugger registered on the computer
> rather than be handled by this dialog box.
> 
> 
>

**Comment by Perfare** [comment]
The path is too long and exceeds 260 characters. You can copy the file to the root directory of the drive. But I will still try to fix this problem.

**Comment by ExplicableOne** [comment]
I get this exact same error and its with a path that is less than 200 characters.

**Comment by hrishikarora** [comment]
Hey @ExplicableOne  did you solved it? I am getting the same error
