### ISSUE TITLE
Texture2d preview error

### ISSUE THREAD

**Issue by glmcdona** [Perfare/UnityStudio#751]
Previewing any Texture2D in the latest AssetStudioGUI v0.15.43 seems to fail with the following error:

```
Preview Texture2D:farhal error

Can't find the resource file sharedassets1.assets.resS

   at AssetStudio.ResourceReader.GetData() in C:\projects\assetstudio\AssetStudio\ResourceReader.cs:line 63

   at AssetStudio.Texture2DConverter..ctor(Texture2D m_Texture2D) in C:\projects\assetstudio\AssetStudioUtility\Texture2DConverter.cs:line 22

   at AssetStudioGUI.AssetStudioGUIForm.PreviewTexture2D(AssetItem assetItem, Texture2D m_Texture2D) in C:\projects\assetstudio\AssetStudioGUI\AssetStudioGUIForm.cs:line 744

   at AssetStudioGUI.AssetStudioGUIForm.PreviewAsset(AssetItem assetItem) in C:\projects\assetstudio\AssetStudioGUI\AssetStudioGUIForm.cs:line 693
```

**Comment by glmcdona** [comment]
Nevermind. User error! The fix was to load the folder of the .asset file in-place instead of just loading the .asset file by itself. I imagine the textures are in the other resource files that were not loaded.
