### ISSUE TITLE
Exception on Sprite crop: Crop rectangle should be smaller than the source bounds

### ISSUE THREAD

**Issue by TheLounger** [Perfare/UnityStudio#772]
```
Export Sprite:UISprite error
Crop rectangle should be smaller than the source bounds.
Parameter name: cropRectangle
   at SixLabors.ThrowHelper.ThrowArgumentException(String message, String name)
   at SixLabors.ImageSharp.Processing.Processors.Transforms.CropProcessor..ctor(Rectangle cropRectangle, Size sourceSize)
   at SixLabors.ImageSharp.Processing.CropExtensions.Crop(IImageProcessingContext source, Rectangle cropRectangle)
   at AssetStudio.SpriteHelper.<>c__DisplayClass2_0.<CutImage>b__0(IImageProcessingContext x) in D:\AssetStudio-master\AssetStudioUtility\SpriteHelper.cs:line 56
   at SixLabors.ImageSharp.Processing.ProcessingExtensions.ProcessingVisitor.Visit[TPixel](Image`1 image)
   at SixLabors.ImageSharp.Processing.ProcessingExtensions.Clone(Image source, Configuration configuration, Action`1 operation)
   at AssetStudio.SpriteHelper.CutImage(Texture2D m_Texture2D, Sprite m_Sprite, Rectf textureRect, Vector2 textureRectOffset, SpriteSettings settingsRaw) in D:\AssetStudio-master\AssetStudioUtility\SpriteHelper.cs:line 56
   at AssetStudio.SpriteHelper.GetImage(Sprite m_Sprite) in D:\AssetStudio-master\AssetStudioUtility\SpriteHelper.cs:line 41
   at AssetStudio.SpriteHelper.GetImage(Sprite m_Sprite, ImageFormat imageFormat) in D:\AssetStudio-master\AssetStudioUtility\SpriteHelper.cs:line 17
   at AssetStudioGUI.Exporter.ExportSprite(AssetItem item, String exportPath) in D:\AssetStudio-master\AssetStudioGUI\Exporter.cs:line 233
   at AssetStudioGUI.Exporter.ExportConvertFile(AssetItem item, String exportPath) in D:\AssetStudio-master\AssetStudioGUI\Exporter.cs:line 363
   at AssetStudioGUI.Studio.<>c__DisplayClass13_0.<ExportAssets>b__0(Object state) in D:\AssetStudio-master\AssetStudioGUI\Studio.cs:line 434
```
[SpriteHelper.cs#L56](https://github.com/Perfare/AssetStudio/blob/master/AssetStudioUtility/SpriteHelper.cs#L56)

Seems like `Rectangle.Ceiling()` can result in going out of bounds for ImageSharp's `Crop()`.
Using `Rectangle.Truncate()` seems to work, but I believe this might result in cropping too much.

**Comment by Perfare** [comment]
After referring to various Sprites, I found that the four parameters need to be processed separately.
I have updated the code and it should be perfect now.

**Comment by TheLounger** [comment]
Great work! Can confirm that it doesn't throw exceptions anymore and that the exported sprites are in line with pre-ImageSharp results.
