### ISSUE TITLE
System.IndexOutOfRangeException

### ISSUE THREAD

**Issue by Rustiness** [Perfare/UnityStudio#804]
```
************** Exception Text **************
System.IndexOutOfRangeException: Index was outside the bounds of the array.
	at AssetStudioGUI.Studio.BuildAssetData() in C:\projects\assetstudio\AssetStudioGUI\Studio.cs:line 137
at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AssetStudioGUI.AssetStudioGUIForm.<BuildAssetStructures>d__55.MoveNext() in C:\projects\assetstudio\AssetStudioGUI\AssetStudioGUIForm.cs:line 206
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
AssetStudioGUI
    Assembly Version: 0.16.0.0
    Win32 Version: 0.16.0
    CodeBase: file:///D:/%EA%B0%9C%EC%9D%B8/APK%20%EB%B6%84%ED%95%B4/AssetStudio.v0.16.0/AssetStudioGUI.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4360.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
AssetStudioUtility
    Assembly Version: 0.16.0.0
    Win32 Version: 0.16.0
    CodeBase: file:///D:/%EA%B0%9C%EC%9D%B8/APK%20%EB%B6%84%ED%95%B4/AssetStudio.v0.16.0/AssetStudioUtility.DLL
----------------------------------------
OpenTK
    Assembly Version: 3.1.0.0
    Win32 Version: 3.1.0
    CodeBase: file:///D:/%EA%B0%9C%EC%9D%B8/APK%20%EB%B6%84%ED%95%B4/AssetStudio.v0.16.0/OpenTK.DLL
----------------------------------------
AssetStudio
    Assembly Version: 0.16.0.0
    Win32 Version: 0.16.0
    CodeBase: file:///D:/%EA%B0%9C%EC%9D%B8/APK%20%EB%B6%84%ED%95%B4/AssetStudio.v0.16.0/AssetStudio.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
Mono.Cecil
    Assembly Version: 0.11.3.0
    Win32 Version: 0.11.3.0
    CodeBase: file:///D:/%EA%B0%9C%EC%9D%B8/APK%20%EB%B6%84%ED%95%B4/AssetStudio.v0.16.0/Mono.Cecil.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
OpenTK.GLControl
    Assembly Version: 3.1.0.0
    Win32 Version: 3.1.0
    CodeBase: file:///D:/%EA%B0%9C%EC%9D%B8/APK%20%EB%B6%84%ED%95%B4/AssetStudio.v0.16.0/OpenTK.GLControl.DLL
----------------------------------------
mscorlib.resources
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_ko_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
AssetStudio.PInvoke
    Assembly Version: 0.16.0.0
    Win32 Version: 0.16.0
    CodeBase: file:///D:/%EA%B0%9C%EC%9D%B8/APK%20%EB%B6%84%ED%95%B4/AssetStudio.v0.16.0/AssetStudio.PInvoke.DLL
----------------------------------------
System.Core.resources
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core.resources/v4.0_4.0.0.0_ko_b77a5c561934e089/System.Core.resources.dll
----------------------------------------
System.Windows.Forms.resources
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_ko_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
```

System.IndexOutOfRangeException: Index was outside the bounds of the array.
This error occurs when reading game data to AssetStudio.v0.16.0.
game data file is attached for analysis.

Game Data Link : https://drive.google.com/file/d/1AoUvcWKnHe2y16loH1aSTT0spG3ep7d_/view?usp=sharing

**Comment by Perfare** [comment]
File is encrypted.
