### ISSUE TITLE
Loading files cause a Array dimensions exceeded supported range error

### ISSUE THREAD

**Issue by aomgar** [Perfare/UnityStudio#973]
```
See the end of this message for details on invoking
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.OutOfMemoryException: Array dimensions exceeded supported range.
   at System.Collections.Generic.List`1.set_Capacity(Int32 value)
   at System.Collections.Generic.List`1.EnsureCapacity(Int32 min)
   at System.Collections.Generic.List`1.Add(T item)
   at AssetStudioGUI.Studio.BuildAssetData() in C:\projects\assetstudio\AssetStudioGUI\Studio.cs:line 216
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AssetStudioGUI.AssetStudioGUIForm.<BuildAssetStructures>d__55.MoveNext() in C:\projects\assetstudio\AssetStudioGUI\AssetStudioGUIForm.cs:line 209
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4470.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
AssetStudioGUI
    Assembly Version: 0.16.40.0
    Win32 Version: 0.16.40
    CodeBase: file:///C:/Users/aomgar/Desktop/Asset%20Studio/AssetStudioGUI.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4488.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4488.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4395.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
AssetStudioUtility
    Assembly Version: 0.16.40.0
    Win32 Version: 0.16.40
    CodeBase: file:///C:/Users/aomgar/Desktop/Asset%20Studio/AssetStudioUtility.DLL
----------------------------------------
OpenTK
    Assembly Version: 3.1.0.0
    Win32 Version: 3.1.0
    CodeBase: file:///C:/Users/aomgar/Desktop/Asset%20Studio/OpenTK.DLL
----------------------------------------
AssetStudio
    Assembly Version: 0.16.40.0
    Win32 Version: 0.16.40
    CodeBase: file:///C:/Users/aomgar/Desktop/Asset%20Studio/AssetStudio.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4470.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
Mono.Cecil
    Assembly Version: 0.11.3.0
    Win32 Version: 0.11.3.0
    CodeBase: file:///C:/Users/aomgar/Desktop/Asset%20Studio/Mono.Cecil.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
OpenTK.GLControl
    Assembly Version: 3.1.0.0
    Win32 Version: 3.1.0
    CodeBase: file:///C:/Users/aomgar/Desktop/Asset%20Studio/OpenTK.GLControl.DLL
----------------------------------------
AssetStudio.PInvoke
    Assembly Version: 0.16.40.0
    Win32 Version: 0.16.40
    CodeBase: file:///C:/Users/aomgar/Desktop/Asset%20Studio/AssetStudio.PInvoke.DLL
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Memory
    Assembly Version: 4.0.1.1
    Win32 Version: 4.6.28619.01
    CodeBase: file:///C:/Users/aomgar/Desktop/Asset%20Studio/System.Memory.DLL
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 4.0.6.0
    Win32 Version: 4.700.19.56404
    CodeBase: file:///C:/Users/aomgar/Desktop/Asset%20Studio/System.Runtime.CompilerServices.Unsafe.DLL
----------------------------------------
K4os.Compression.LZ4
    Assembly Version: 1.1.11.0
    Win32 Version: 1.1.11
    CodeBase: file:///C:/Users/aomgar/Desktop/Asset%20Studio/K4os.Compression.LZ4.DLL
----------------------------------------
System.Buffers
    Assembly Version: 4.0.3.0
    Win32 Version: 4.6.28619.01
    CodeBase: file:///C:/Users/aomgar/Desktop/Asset%20Studio/System.Buffers.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by aomgar** [comment]
[Sample.zip](https://github.com/Perfare/AssetStudio/files/8645671/Sample.zip)

**Comment by aomgar** [comment]
The issue seems to be fixed when I downloaded AssetStudio.net6.v0.16.40.zip instead of AssetStudio.net472.v0.16.40.zip
