### ISSUE TITLE
Opening file fails to load Material

### ISSUE THREAD

**Issue by Backman** [Perfare/UnityStudio#987]
AssetStudio fails to load Material type from `unity_default_resources`.
[The files is generated using Unity 2021.3.2f1](https://we.tl/t-CWB9xi1Z2h)
```
System.OverflowException: Arithmetic operation resulted in an overflow.
   at AssetStudio.UnityPropertySheet..ctor(ObjectReader reader) in /AssetStudio/AssetStudio/Classes/Material.cs:line 55
   at AssetStudio.Material..ctor(ObjectReader reader) in /AssetStudio/AssetStudio/Classes/Material.cs:line 119
   at AssetStudio.AssetsManager.ReadAssets() in /AssetStudio/AssetStudio/AssetsManager.cs:line 427
```

**Comment by Perfare** [comment]
2021.3 has been supported.
